k8sgpt-ai/k8sgpt

- cmd/root.go
> chore: update root.go path

- pkg/analyzer/serviceAnalyzer.go
> fix: this stops service exiting the program

- .github/ISSUE_TEMPLATE.md
Closes #96
Added a default issue template for GitHub.
> chore: added default issue template (#96)

- README.md
- Adds documentation for WSL workaround
- Fixes indentation
> docs: add wsl gcc instructions

- SECURITY.md
> feat: security.md

- README.md
Closes #134 
Update Readme with new slack link. [https://k8sgpt.slack.com/](https://k8sgpt.slack.com/)
> docs: add new slack link (#134)

- README.md
Quick update to specify Homebrew error to call out WSL and Linux on the Readme.
> readme update to specifiy WSL and Linux

- pkg/analyzer/ingressAnalyzer.go
Closes #140
This commit adds a check to the ingress analyzer that verifies whether the secret declared in the ingress exists on the cluster. This helps to ensure that only valid secrets are used in the ingress configuration.
> feat: add secret validation to ingress analyzer

- cmd/analyze/analyze.go
A tiny PR to fix a typo in the description of the filter flag in analyze command
> fix: typo in description of the filter flag in analyze command

- cmd/analyze/analyze.go
Fixes output issue in https://github.com/k8sgpt-ai/k8sgpt/pull/144
> fix: bugfix for output

- cmd/root.go
Commented out the sample flag that the framework comes with, as it was not in use. Choose to comment it out for now for easy reference, just in case we want to implement that type of toggle flags.
> refactor: removed sample flag

- cmd/auth/auth.go
Closes # 
Added an output of the selected backend type
> feat: output selected backend

- pkg/analyzer/ingressAnalyzer.go
Closes # 
The commit adds functionality to validate whether the Ingress resource specifies a valid Ingress class or not. If no Ingress class is specified, a message will be returned indicating that an Ingress class needs to be specified. If an Ingress class is specified, the code will validate whether it exists or not.
> feat: add Ingress class validation

- cmd/root.go
- pkg/kubernetes/kubernetes.go
> fix: now supports different kubeconfig and kubectx

- cmd/analyze/analyze.go
Closes # 
The details of the analysis during `--explain` were no longer displayed.
> fix: analysis detail not displayed when --explain

- README.md
> feat: adding shields to readme

- cmd/filters/filters.go
Closes #187
Updated the alias in `filters.go` to `filter`.
> feat: alias filter to filters

- pkg/analyzer/analyzer.go
- pkg/analyzer/hpaAnalyzer.go
- pkg/analyzer/ianalyzer.go
- pkg/analyzer/ingressAnalyzer.go
- pkg/analyzer/pdbAnalyzer.go
- pkg/analyzer/podAnalyzer.go
- pkg/analyzer/pvcAnalyzer.go
- pkg/analyzer/rsAnalyzer.go
- pkg/analyzer/serviceAnalyzer.go
> feat: analyzer ifacing

- .github/workflows/test.yaml
- go.mod
- go.sum
- pkg/analyzer/events.go
- pkg/analyzer/podAnalyzer_test.go
- pkg/analyzer/serviceAnalyzer_test.go
- pkg/kubernetes/kubernetes.go
> feat: adding unit testing and example

- cmd/analyze/analyze.go
- pkg/analysis/analysis.go
> fix: regression on dynamic filters

- .github/workflows/test.yaml
* Runs tests on PRs instead of on push
> ci: run tests on PR (main)

- README.md
Closes # 
Adding the STS analyzer in the README file.
> docs: add statefulSet analyzer in the docs.

- .github/CODEOWNERS
> chore: adding k8sgpt-approvers

- pkg/analysis/analysis_test.go
Closes # 
It doesn't fix any already mentioned issues
This PR updates analysis_test.go and upgrades its readablity
> fix: updated analysis_test.go

- pkg/kubernetes/kubernetes.go
> chore: added oidc

- README.md
- go.mod
- go.sum
- pkg/analyzer/analyzer.go
- pkg/analyzer/cronjob.go
- pkg/analyzer/cronjob_test.go
- pkg/analyzer/deployment.go
- pkg/analyzer/deployment_test.go
- pkg/analyzer/netpol.go
- pkg/analyzer/netpol_test.go
- pkg/common/types.go
- pkg/util/util.go
> chore: additional analyzers

- cmd/serve/serve.go
Closes # 
When starting the server we retrieved the `backend_type` and `$backend_key` keys (which are deprecated configuration keys) instead of the AiProvider.
> fix: use the aiProvider object when launching the server

- pkg/integration/integration.go
Closes #278 
Resolves the issue where running `k8sgpt integration activate trivy` multiple times could result in duplicate entries in the vulnerabilityreport filters list. This fix ensures that the filters list only includes unique entries, resolving the issue of duplicated filters.
Activate :
```bash
(matthisholleville) ➜  k8sgpt git:(main) ✗ ./k8sgpt integration activate trivy
Activated integration trivy
(matthisholleville) ➜  k8sgpt git:(main) ✗ ./k8sgpt integration activate trivy
Integration already activated : VulnerabilityReport
```
Deactivate : 
```bash
(matthisholleville) ➜  k8sgpt git:(main) ✗ ./k8sgpt integration deactivate trivy
Deactivated integration trivy
(matthisholleville) ➜  k8sgpt git:(main) ✗ ./k8sgpt integration deactivate trivy
Ingregation trivy does not exist in …
```
> fix: resolve issue with duplicated integration filters.

- cmd/analyze/analyze.go
- pkg/analysis/analysis.go
- pkg/server/server.go
Closes #289 
modify error handling to return a list of errors to display to the user at the end of analysis without blocking it if an error is detected (e.g., version of an object is not available on user's cluster)
```bash
(matthisholleville) ➜  k8sgpt git:(main) ✗ ./k8sgpt analyze --namespace k8sgpt
Error: CronJob the server could not find the requested resource
0 k8sgpt/fake-hpa(fake-hpa)
- Error: HorizontalPodAutoscaler uses StatefulSet/fake-deployment as ScaleTargetRef which does not exist.
```
> feat: modify analyze error handling

- pkg/ai/iai.go
- pkg/ai/noopai.go
- pkg/ai/openai.go
- pkg/ai/prompts.go
- pkg/analysis/analysis.go
Closes # 
Refactoring the way we configure k8sgpt ai providers by adding an interface.
This PR is a prerequisite for adding azure openai and llama providers.
> feat: add configuration interface to support customer providers

- container/dashboards/k8sgpt-dashboard.json
Closes #295 
Add K8sGPT Grafana dashboard.
> feat: add k8sgpt grafana dashboard

- README.md
Closes # 
Add `serve` & `integrations` documentation to README.
> feat: add serve & integration to README

- .github/workflows/golangci_lint.yaml
Closes #330 
In order to catch a variaty of small and quick to happen mistakes, there is now an additional action in place which runs a linter on the PR content.
> feat: introduce linter to run on PR builds

- cmd/serve/serve.go
- pkg/ai/prompts.go
- pkg/analyzer/cronjob.go
- pkg/analyzer/netpol.go
This PR fixes the following linter reported issues:
* Removal of some dead code
* use correct result slice for cronjob analyzer
> fix: various linter reported issues

- LICENSE
This PR is to update the Apache2 license to include the critical clause on line 190 relating to defining the first commit date year and the new way of defining the authors as per the license.
Its PR will contribute to closing https://github.com/k8sgpt-ai/k8sgpt/issues/341 once all checkboxes are ticked for all repos in the org.
> chore: update Apache2 license Authors

- README.md
> fix: link to documentation

- .github/CODEOWNERS
- .github/settings.yml
* Adds settings file for repo configuration
> chore: add settings

- README.md
> feat: improving readme

- CONTRIBUTING.md
Update the Slack URL in CONTRIBUTING.md to match the URL in README.md
> fix: update CONTRIBUTING.md Slack URL

- container/dashboards/k8sgpt-dashboard.json
Closes # 
NA
the original PNG file was missing. Replace it with an existing new logo.
Tested
> chore: fix the logo URL

- charts/k8sgpt/templates/service.yaml
- charts/k8sgpt/templates/serviceMonitor.yaml
Closes # 
Use correct port to get metrics.
> feat: use correct port to metrics

- charts/k8sgpt/Chart.yaml
- charts/k8sgpt/templates/rolebinding.yaml
Closes # 
Use templated name to clusterrolebinding & bump version to 0.3.0
> fix: clusterole name

- README.md
- cmd/auth/auth.go
- cmd/auth/remove.go
Closes # 
This commit adds a new command to the auth package called "remove", which allows users to remove a backend AI provider from the configuration file.
> feat: add remove command to remove a backend AI provider

- cmd/auth/new.go
Closes # 
Minor fix to place engine CMD flag under `auth new` layout
> fix: update engine's cmd flag to match the new cli layout

- .github/workflows/test.yaml
- README.md
- cmd/auth/remove.go
- cmd/cache/add.go
- cmd/cache/cache.go
- cmd/cache/list.go
- cmd/cache/remove.go
- cmd/root.go
- go.mod
- go.sum
- pkg/analysis/analysis.go
- pkg/cache/cache.go
- pkg/cache/file_based.go
- pkg/cache/s3_based.go
Closes # 
- Refactor README.md to reduce the amount of sprawl of information
- Introduce s3 based caching support #381 #209
> feat: caching

- cmd/cache/list.go
> fix: updated list.go to handle k8sgpt cache list crashing issue

- cmd/version.go
Closes #462
Fixed typo in `k8sgpt version` command.
> fix: typo in `k8sgpt version`

- pkg/cache/cache.go
- pkg/cache/s3_based.go
> feat: fix for s3 cache from operator

- go.mod
- go.sum
> feat: upgrading the proto files to fix user issues

- pkg/analyzer/mutating_webhook.go
Closes #  #566
Check absent service from mutating webhook as well, it causes panic errors atm
> chore: continue on absent service

- go.mod
- go.sum
- pkg/ai/cohere.go
> Revert "chore: upgraded cohere backend"

- pkg/kubernetes/kubernetes.go
> fix: --kubeconfig doesn't work (revert)

- go.mod
- go.sum
- pkg/analyzer/analyzer.go
> chore: updated protobuf libs

- go.mod
- go.sum
> chore: updated schema for integrations support

- pkg/analyzer/analyzer.go
> chore: slice loop replace

- pkg/integration/trivy/analyzer.go
Closes # 
namespace parameter was not honored in trivy analyzerT
> fix: respect namespace scope in trivy analyzer

- go.mod
> fix: emergency fix for bad package revision in go mod

- pkg/analyzer/pdb.go
> fix: pdb panic error guard

- pkg/integration/trivy/trivy.go
> feat: added create namespace on deploy

- renovate.json
* Enables Automerge for Renovate PRs (still need approval, but will merge on approval)
> chore: enable automerge for renovate

- .github/workflows/release.yaml
* Pins to a more specific release please version (to better detect changes)
> chore: pin release-please version

- README.md
> chore: update slack link

- README.md
Fix the documentation to use grpcul instead curl as Analysis with serve mode command
> docs: use grpcurl instead curl

- .github/workflows/test.yaml
> feat: coverage reports

- .goreleaser.yaml
As the project is distributed with the Apache 2.0 license. Linux packages should also probably distributed with the Apache 2.0 license.
> chore: set correct license during package build

- pkg/analyzer/validating_webhook_test.go
This commit introduces comprehensive tests for the validating webhook analyzer defined in the `pkg/analyzer` package.
Adding these tests increases the code coverage of the `validating_webhook.go` file to almost 95%.
> test: added tests for validating webhook analyzer

- pkg/analyzer/rs_test.go
This commit introduces comprehensive tests for the ReplicaSet analyzer defined in the `pkg/analyzer` package.
Adding these tests increases the code coverage of the `rs.go` file to  >95%.
> test: added tests for the ReplicaSet analyzer

- renovate.json
Closes # 
We experience an inflation of PRs from renovate, this is a first attempt to try and group dependencies to ease the reviewing process of renovate bot PRs
https://docs.renovatebot.com/noise-reduction/
> chore: attempt to group renovate deps

- pkg/analyzer/pdb_test.go
- pkg/analyzer/pvc_test.go
- pkg/util/util_test.go
- Removed test cases which required access to `/root` from the `pkg/util` package.
- Fixed flaky `PodDisruptionBudget` test.
> test: fixed various flaky tests

- pkg/kubernetes/apireference_test.go
- pkg/kubernetes/kubernetes_test.go
- pkg/kubernetes/testdata/kubeconfig
This commit increases the code coverage of the `pkg/kubernetes` package to 94%
> test: added tests for the pkg/kubernetes package

- .github/workflows/test.yaml
- renovate.json
> feat: codecov

- pkg/analyzer/ingress_test.go
- Added missing test cases to ensure proper testing of the Ingress analyzer. The addition of these missing test cases has increased the code coverage of this analyzer to over 97%.
Partially Addresses: https://github.com/k8sgpt-ai/k8sgpt/issues/889
> test: added missing tests for the Ingress analyzer

- cmd/auth/list.go
Closes #936
Because the feature of show password has been removed by https://github.com/k8sgpt-ai/k8sgpt/pull/695.
So clean the code of `userInput`
> fix: remove show password in `auth list`

- README.md
add log analyzer in analyzer list
add `logAnalyzer` in analyzer list
Closes #
> docs: add logAnalyzer in README.md 

- pkg/integration/prometheus/prometheus.go
fix(deps): typo in prometheus.go
> fix(deps): typo in prometheus.go

- .goreleaser.yaml
> chore: update goreleaser ldflags

- .goreleaser.yaml
> chore: fixed the goreleaser file

- .github/workflows/release.yaml
> chore: updated the goreleaser action

- pkg/analysis/analysis.go
> feat: missing errors in custom analysis

- renovate.json
> chore: renovate.json

- .github/workflows/release.yaml
> chore: updated to use CNCF runners

- .github/workflows/release.yaml
> feat: test revert runner on release job

- .github/workflows/release.yaml
- go.sum
> feat: free disk

- .github/workflows/build_container.yaml
- .github/workflows/golangci_lint.yaml
- .github/workflows/release.yaml
- .github/workflows/semantic_pr.yaml
- .github/workflows/test.yaml
> feat: updated runners to enterprise

- .github/workflows/build_container.yaml
- .github/workflows/golangci_lint.yaml
- .github/workflows/release.yaml
- .github/workflows/semantic_pr.yaml
- .github/workflows/test.yaml
> feat: reverting the cncf runners

- go.mod
- pkg/cache/interplex_based.go
- pkg/server/config/config.go
> feat: fixed missing cache params

- README.md
docs: fix broken schema link in README.md
> docs: fix broken schema link in README.md

- pkg/ai/amazonbedrock.go
Mumbai Region [ap-south-1] addition in AI-Amazon Bedrock.
> chore: Adding region

- README.md
When copy install command from README.md, the $ sign will trigger error.
```
$ brew install k8sgpt                                                                                                                       
$: command not found
```
> docs: remove extra dollar sign in README.md

- README.md
This pull request updates the README.md file to:
1. Add a Table of Contents for better readability and navigation.
2. Resolve a typo: "RepicaSet" is corrected to "ReplicaSet".
3. Remove extra spaces to clean up formatting and minor issues with phrasing
> docs: add table of contents and cleanup

- go.mod
- go.sum
> chore: updating deps

- .github/workflows/build_container.yaml
> chore: fix workflows

- .github/workflows/build_container.yaml
> chore: fixing docker build push action

- .github/workflows/build_container.yaml
- .github/workflows/release.yaml
> chore: updated actor for login

- .github/workflows/release.yaml
> chore: removed krew release

- README.md
Closes # 
Fix the slack invite link.
Fix #1443.
> docs: fix the slack invite link

- go.mod
- pkg/ai/factory.go
- pkg/server/query/query.go
- pkg/server/query/query_test.go
Closes #1445 
1. sets up client for given configuration in Query()
2. add unit test for the query.go
> fix: config ai provider in query

- .goreleaser.yaml
- go.mod
- go.sum
> feat: slack announce

- pkg/ai/amazonbedrock.go
- pkg/ai/amazonbedrock_test.go
- pkg/ai/bedrock_support/completions_test.go
Closes # 
Using modelname when calling completion, so inference profile ARN could be used in addition to model ID.  A Docker image is build and is tested with a inference profile
> feat: using modelName will calling completion

- .github/workflows/release.yaml
> feat: added token for goreleaser

- pkg/ai/amazonbedrock.go
Closes https://github.com/k8sgpt-ai/k8sgpt/issues/1391
**Description**
This PR adds support for Messages API for Claude 3.5 v1/v2
> fix(deps): adding fixes to switch Messages API issue 1391

- pkg/ai/amazonbedrock.go
> feat: fix to broken inference
