k8sgpt-ai/k8sgpt

README.md

Closes  #105
* Improved current README by adding clear windows installation steps with path configuration.

docs: added Windows and Linux instalation steps in README  

---

README.md
cmd/analyze/analyze.go
pkg/analyzer/analysis.go
pkg/analyzer/analyzer.go
pkg/analyzer/podAnalyzer.go
pkg/analyzer/pvcAnalyzer.go
pkg/analyzer/rsAnalyzer.go
pkg/analyzer/serviceAnalyzer.go

feat: added namespace filter

---

pkg/analyzer/ingressAnalyzer.go
pkg/util/util.go

Closes # 
A merge request that includes the modifications made in [arbreezy](https://github.com/arbreezy) merge request available https://github.com/k8sgpt-ai/k8sgpt/pull/143 and adds Ingress to the switch case GetParents.

fix: ingress object meta value

---

README.md
cmd/filters/filters.go
cmd/filters/filtersList.go
cmd/root.go
pkg/analyzer/analyzer.go

Closes # 
As mentioned in this issue https://github.com/k8sgpt-ai/k8sgpt/issues/158, this PR adds a command to list the available filters.

feat: add filter command add "list" subcommand

---

cmd/root.go

Closes #164
As @Antvirf pointed out in their issue https://github.com/k8sgpt-ai/k8sgpt/issues/164, the `kubecontext` flag was not being taken into account. To fix this issue, I moved the context initialization to the `initConfig` method.
Based on my tests, it is now functional : 
```
➜  k8sgpt git:(main) ✗ ./k8sgpt --kubecontext existing-context analyze --namespace my-ns -o json 
{ "status": "OK" }
➜  k8sgpt git:(main) ✗ ./k8sgpt --kubecontext fakeContext analyze --namespace my-ns -o json 
Error initialising kubernetes client: context "fakeContext" does not exist
➜  k8sgpt git:(main) ✗ ./k8sgpt analyze --namespace my-ns -o json 
{ "status": "OK" }
```

fix: kubecontext flag has no effect

---

pkg/analyzer/hpaAnalyzer.go

Closes # 
The hpaAnalyzer is using the `Ingress.ObjectMeta` instead of the `HorizontalPodAutoscalers.ObjectMeta` to get its parent.

fix: hpaAnalyzer analysis result is using wrong parent

---

README.md
pkg/analyzer/analysis.go
pkg/analyzer/analyzer.go
pkg/analyzer/events.go
pkg/analyzer/pdbAnalyzer.go
pkg/analyzer/podAnalyzer.go
pkg/analyzer/pvcAnalyzer.go

Closes #163
This PR adds a PDB analyzer, which checks all PDBs if their selector configuration matches any existing pods. The filter is disabled by default and can be activated with `k8sgpt filters add PodDisruptionBudget`.
```
k8sgpt filters list
Active:                                                                                                                                                                                                            
> ReplicaSet                                                                                                                                                                                                       > PersistentVolumeClaim …
```

feat: add pdb analyzer

---

README.md
cmd/auth/auth.go

Closes #180 
The code modification added a password flag for backend authentication in the auth package. Previously, users had to enter their password in the terminal when authenticating with the chosen backend, but with this modification, they can provide the password as a flag when running the authentication command.

feat: add password flag for backend authentication

---

.github/workflows/release.yaml
.goreleaser.yaml
cmd/generate/generate.go

* Creates DEB, RPM, APK packages

chore: create linux packages

---

cmd/analyze/analyze.go
go.mod
pkg/analysis/analysis.go
pkg/analysis/analysis_test.go

* Decouple analysis and output (analyze -> AI analysis -> output)
* Add structure for Json Output
* Add problem count and overall status to JSON, use jsonIndent to make it better readable
* Report "No issues found" in text output if nothing is found
* Use this structure for success too
* Move output generation to analysis to make it re-usable e.g. in API, operator
* First tests for json output

chore: prettier json output and output improvements

---

cmd/analyze/analyze.go
cmd/auth/auth.go
pkg/ai/ai.go
pkg/ai/iai.go

Closes #167
It is now possible to specify the model to use during analysis.
This commit adds support for a new configuration format that is not backwards compatible with the previous format. This is a breaking change and requires users to update their configuration files to use the new format.
BREAKING CHANGE: The format of the configuration file has changed. Users must update their configuration files to use the new format.
Last configuration format : 
```yaml
backend_type: openai
openai_key: xxxxxx
```
New configuration format : 
```yaml
ai:
providers:
- name: openai
model: gpt-3.5-turbo
password: xxxxxx
```
If the configuration format is incorrect : 
```bash
➜  k8sgpt git:(feature/config-new-format) ✗ ./k8sgpt analyze --namespace k8sgpt --explain --no-cache
Error: AI provider not …
```

feat!: add support for new configuration format

---

pkg/analyzer/analyzer.go
pkg/analyzer/statefulset.go
pkg/analyzer/statefulset_test.go
pkg/analyzer/types.go

Closes # 
This PR adds a StatefulSet analyser which only checks if the service which is specified in ServiceName, exists.

feat: introduce StatefulSet analyser.

---

pkg/analyzer/statefulset.go
pkg/analyzer/statefulset_test.go

Closes # 
This PR adds a check against missing storage class resources in a StatefulSet's VolumeClaimTemplate
A missing storage class will be caught also from the PVC analyzer with a more generic error ` Error: storageclass.storage.k8s.io "example-storage-class" not found`.
I believe adding the storage class analysis in StatefulSets will provide a better explanation to the end user.
I see PVC analyzer as a more generic underlying mechanism to report generic issues/events in a cluster but eager to get any feedback where to draw the line for possible overlapping issues.

feat: add storage class names' check.

---

pkg/analyzer/hpa.go

Closes #229 #216
Fixed a bug that did not retrieve the correct namespace when analyzing HPA.

fix: use hpa namespace instead analyzer namespace

---

pkg/ai/openai.go
pkg/analysis/analysis.go

Closes #99
Properly exit the progressbar on error to avoid the missing newline mentioned in issue #99.

fix: exit progressbar on error to fix missing newline

---

cmd/version.go

Closes [#262](https://github.com/k8sgpt-ai/k8sgpt/issues/262) 
Add a new line after the version command output.
Before
```
./k8sgpt version
k8sgpt version dev%
```
After
```
./k8sgpt version
k8sgpt version dev
```

fix: add new line after version cmd output

---

cmd/root.go
cmd/serve/serve.go

Closes # 
#265 
This checks the envs for starting a server to allow this to run in K8s

feat: envs to initialise server

---

pkg/server/log.go
pkg/server/server.go

Closes # 
This code adds middleware logging functionality to a server, allowing it to log every request executed. The logger used in this implementation is the `zap` logging library.
Log format : 
```bash
{"level":"error","ts":1681677987.851809,"msg":"unsupported output format: fake. Available format json,text\n","duration_ms":1255,"method":"GET","remote_addr":"127.0.0.1:63095","status_code":500,"url":"/analyze","stacktrace":"xxxxxx"}
{"level":"info","ts":1681678081.765677,"msg":"request completed","duration_ms":1100,"method":"GET","remote_addr":"127.0.0.1:63100","status_code":200,"url":"/analyze"}
```

feat: init logging middleware on server mode

---

pkg/util/util.go

Closes # 
The previous implementation of the EnsureDirExists function only created a
single directory, which resulted in an error if the parent directories did
not exist. This fix updates the function to create parent directories
recursively using `os.MkdirAll`.

fix: ensure parent directories are created in EnsureDirExists function

---

pkg/analyzer/cronjob.go
pkg/analyzer/cronjob_test.go
pkg/analyzer/deployment.go
pkg/analyzer/deployment_test.go
pkg/analyzer/hpaAnalyzer_test.go
pkg/analyzer/ingress_test.go
pkg/analyzer/netpol_test.go
pkg/analyzer/pod_test.go
pkg/analyzer/service_test.go
pkg/analyzer/statefulset_test.go

Closes # 
These changes address an issue with the Cronjob and Deployment analyzers. The `namespace` flag was not being taken into account for these two analyzers, resulting in returning all deployments/cronjobs from all namespaces of a cluster even if the `--namespace` flag was specified.
I took the opportunity to add tests to the existing analyzers to prevent regressions in the future.

fix: deployment/cronjob analyzers namespace filtering

---

pkg/ai/noopai.go
pkg/ai/openai.go
pkg/util/util.go

Closes #294 
The cache key calculation has been updated to include the `language` parameter in addition to the `name` and `sEnc` parameters.
```bash
(matthisholleville) ➜  k8sgpt git:(main) ✗ ./k8sgpt analyze --namespace k8sgpt --language "english" --explain --no-cache
100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1/1, 14 it/min)        
0 k8sgpt/fake-hpa(fake-hpa)
- Error: HorizontalPodAutoscaler uses StatefulSet/fake-deployment as ScaleTargetRef which does not exist.
The Kubernetes error message means that the HorizontalPodAutoscaler is referring to a target called "fake-deployment" which does not exist. To fix this error, you need to update the target of the HorizontalPodAutoscaler to refer to a valid …
```

fix: resolve language toggle bug (issue #294)

---

.gitignore
Makefile

Closes #305 
Read the proposal #305 for the Makefile design
This will give you more information at build time:
```bash
❯ make build
go version go1.20 linux/amd64
===========> Building binary /root/workspaces/k8sgpt/bin/k8sgpt *[Git Info]: v0.2.4-13b2a1314f59d2a15a159a622c07596af22ffa31
```

feat: the overall optimization and architecture design of the makefile are made

---

pkg/ai/iai.go
pkg/ai/noopai.go
pkg/ai/openai.go
pkg/analysis/analysis.go
pkg/cache/cache.go
pkg/cache/file_based.go
pkg/cache/noop.go

Closes #323
Instead of storing cached values in the config yaml, they are now stored under these OS specific locations:
* Linux: `~/.cache/k8sgpt`
* MacOS: `~/Library/Caches`
* Windows: `%LocalAppData%\cache`
Additionally a `Cache` package and interface has been introduced. Currently there are two implementations:
* Noop - Doesn't do anything
* FileBased - Stores data in files under the locations listed above
- [] My code requires changes to the documentation

feat: use OS conform path for storing cached results

---

pkg/analysis/analysis.go

Before the filter inside the func literal was capturing the value from the outer loop. This is a subtle mistake, since in combination with running the function literal as go routine, the value of filter could have already changed at invocation time.
To fix this, the filter is now passed in as an argument to the func literal.

fix: explicitly pass in filter to async analysis go routine

---

cmd/auth/auth.go
pkg/ai/iai.go

Closes # 
Small PR to improve the UX of k8sgpt cli.  
We won't ask for a password in the terminal if backend is localai and password hasn't been set explicitly

feat: don't ask for password if backend is localai

---

cmd/analyze/analyze.go
cmd/root.go
pkg/analysis/analysis.go
pkg/analysis/analysis_test.go
pkg/analysis/output.go
pkg/server/server.go

Closes #325 
I have revamped the error handling to ensure that they are included and adhere to the output format. Now we have an `errors` attribute in the `Analysis` object that collects all the errors and displays them based on the output selected by the user.
I also deleted some not useful logs on configuration management

feat: rework output format

---

pkg/server/log.go

feat: add error message if analyze request fail

---

cmd/auth/auth.go
cmd/auth/new.go
cmd/filters/filters.go
cmd/filters/list.go
cmd/integration/integration.go
cmd/root.go
pkg/analysis/analysis.go
pkg/analyzer/node.go
pkg/analyzer/pod.go
pkg/server/server.go

Closes #404 
Fix part of the lint errors.
But I didn't fix them all 
(1)Some health relevant code  and unused functions I believe will be refine later by their authors?
(2) For code `cmd/generate/generate.go:43`, I don't understand what it means by `override the default backend if a flag is provided`.
So there are some issues left as below, later when they are all fixed, we can enable lint test in CI as PR Gate:
```
make lint
INFO [lintersdb] Active 7 linters: [errcheck gosimple govet ineffassign staticcheck typecheck unused]
cmd/generate/generate.go:43:4: ineffectual assignment to backendType (ineffassign)
backendType = backend
^
pkg/server/server.go:41:2: field `maxConcurrency` is unused (unused)
maxConcurrency int
^
pkg/server/server.go:53:5: var `health` is unused (unused)
var health …
```

chore: make go-lint happy

---

go.mod
go.sum
pkg/analysis/analysis.go
pkg/server/handler.go

Closes # 
This pull request includes two commits that address different aspects of the codebase:
1. Fix: Stop execution after matching condition in `RunAnalysis()`
This commit fixes an issue in the `RunAnalysis()` function where the execution continued even after matching a condition. With this fix, the execution now stops at the end of the corresponding if statement, improving control flow.
2. Feat: Include filters parameter in `AnalyzeRequest` initialization
This commit adds a new feature to the `AnalyzeRequest` initialization. It includes the filters parameter, allowing for more specific analysis by specifying filters during the analysis process.
```bash
grpcurl -plaintext -d '{"explain": false, "nocache": false, "filters": ["Ingress"], "namespace": "k8sgpt"}' localhost:8080 …
```

feat: filters api

---

.github/workflows/test.yaml
pkg/ai/noopai.go
pkg/analyzer/hpaAnalyzer_test.go
pkg/analyzer/node.go

Closes #NA
Fix some files detected by `make fmt`
Add `make test` and `make fmt` into Github Action. `make lint` is not added until all lint problems fixed(refer to comment in https://github.com/k8sgpt-ai/k8sgpt/pull/405)
- [NA] My code requires changes to the documentation
- [NA] I have updated the documentation as required

chore: gofmt fix and enable in CI

---

README.md
cmd/auth/auth.go
cmd/auth/default.go
cmd/auth/list.go
pkg/ai/iai.go
pkg/analysis/analysis.go
pkg/analysis/output.go
pkg/cache/s3_based.go

feat: added the ability to set a user default AI provider

---

cmd/auth/remove.go

Closes # 
The commit fixes an issue where the `--backend` option was not properly validated in the `remove` command.
Previously, the command did not check if the `--backend` option was set, leading to potential errors. This fix ensures that the option is required and throws an error if it is missing.

fix: missing validation for backend option in remove command

---

pkg/analysis/analysis.go
pkg/analyzer/analyzer.go

Closes #431 
- [] My code requires changes to the documentation

fix: use coreAnalyzer if there are no filters selected and no active

---

README.md
cmd/auth/add.go
cmd/auth/auth.go
cmd/auth/remove.go

Closes #437 
This PR includes two commits:
1. feat: Rework "auth remove" command for improved consistency with other remove commands, such as "filters remove".
2. feat: Rename "auth new" command to "auth add". This modification enhances consistency throughout the codebase.
These changes aim to enhance the overall consistency and maintainability of the codebase by aligning command names and behaviors.

feat: rework auth commands

---

cmd/cache/add.go
cmd/cache/remove.go
go.mod
go.sum
pkg/cache/cache.go
pkg/server/analyze.go
pkg/server/config.go
pkg/server/handler.go
pkg/server/server.go

Closes #449 
Initialize the configuration API route and add cache support
Examples : 
`AddCache` : 
```bash
grpcurl -plaintext -d '{
"cache": {
"region": "us-west-1",
"bucketName": "my-cache-bucket"
}
}' localhost:8080 schema.v1.Server/AddConfig
{
"status": "Configuration updated."
}
```
`RemoveCache` :
```bash
grpcurl -plaintext -d '{
"cache": {
"bucketName": "my-cache-bucket"
}
}' localhost:8080 schema.v1.Server/RemoveConfig
{
"status": "Successfully removed the remote cache"
}
```

feat: add configuration api route

---

charts/k8sgpt/templates/deployment.yaml

While the name in the ServiceAccount ressource is "k8sgpt.fullname", the reference in the deployment is hardcoded "k8sgpt". If you install the helm chart with a different release name than "k8sgpt", the deployment won't start because the SA "k8sgpt" is not found.

fix: name of sa reference in deployment

---

README.md

Closes # 
docs: fix add localai command in readme.md

docs: fix add localai command in readme.md

---

cmd/integration/integration.go
pkg/ai/prompts.go

Fixes `intergration` typos in CLI help text

fix: 'intergration' typos

---

cmd/root.go

Closes # 
On app start it shows default config file location as $HOME/.k8sgpt.yaml which is different for different OS.
I've updated the code to show the correct location according to users OS on app start.
OLD
New

fix: displaying correct yaml config location on app start

---

cmd/cache/list.go
cmd/integration/activate.go
pkg/integration/integration.go

Closes #534
Use Case:
This flag is helpful, for example, I ran `k8sgpt` command in local machine, but the k8s cluster runs remotely.
I've activated the plugin remotely, but local k8sgpt.conf didn't reflect it.
so this flag helps my local config file to catch up the real situation.
- [] My code requires changes to the documentation
- [] I have updated the documentation as required
(1) Before `activate trivy`: 
(2) helper message:
(3) activate without install it

fix: add --no-install for activate command

---

pkg/analyzer/analyzer.go
pkg/analyzer/mutating-webhook.go
pkg/analyzer/validating-webhook.go
pkg/common/types.go
pkg/util/util.go

Closes #533 
Changes made:
- Added an analyzer for Validating Webhook that checks if the pod that webhook points to is not active.
- Added an analyzer for Mutating Webhook that checks if the pod that webhook points to is not active.

feat: add Validating/Mutating webhook analyzer

---

pkg/analyzer/validating_webhook.go

chore: fixing edge cases with missing wh service

---

README.md
go.mod
go.sum
pkg/ai/cohere.go
pkg/ai/iai.go

This PR adds [Cohere](https://cohere.com) has an AI backend. Cohere has a [free-tier](https://txt.cohere.com/free-developer-tier-announcement/) to allow experimentations
In the future, it may be interesting to create a [finetuned model](https://docs.cohere.com/docs/training-custom-models) from runbooks to improve the quality of the responses.
**Disclaimer:** I am a new hire at Cohere and wrote that to experiment with the product, Cohere will not provide official support for `k8sgpt`.

feat: add Cohere backend

---

pkg/kubernetes/kubernetes.go

fix: --kubeconfig doesn't work

---

pkg/kubernetes/kubernetes.go

Closes #604 
There is a use case where people will run k8sgpt within a _management_ cluster, as a pivot to other clusters where they can define explicitly the kubeconfig. 
This small PR hopefully addresses that case by ensuring whenever `kubeconfig` is defined we will use it to create the k8s client even if k8sgpt is running in a cluster

fix: use-case while in cluster, connecting to an external

---

pkg/integration/integration.go
pkg/integration/trivy/trivy.go

chore: fixes a bug where filters do not deactivate

---

CONTRIBUTING.md
README.md
SECURITY.md

fix: typos

---

pkg/ai/prompts.go
pkg/integration/trivy/analyzer.go

Closes #590
in addition to #609 we should show each check of the ConfigAuditReport similar to the VulnerabilityReport. Then the user gets more insights what the security issues are and also the AI can give you better solutions.
Also, I added a specific AI prompt for the ConfigAuditReport kind to get better AI results.

feat: show each ConfigAuditReport check

---

pkg/analyzer/mutating_webhook.go
pkg/analyzer/validating_webhook.go

Closes #647  
This PR fixes potential panic issues when service selector is empty for a service defined in {mutating,validating} webhook K8s resources.
It will now continue on their absence and effectively defer the analysis to the service analyser.

fix: defer to service analyser when selectors are missing

---

README.md
cmd/auth/add.go
cmd/auth/auth.go
cmd/auth/update.go
pkg/ai/azureopenai.go
pkg/ai/cohere.go
pkg/ai/iai.go
pkg/ai/openai.go

Because when k8sgpt talks with vLLM, the default MaxToken is 16, which is so small.
Given the most model supports 2048 token(like Llama1 ..etc), so put here for a safe value.
Closes # NA
When k8sgpt talks with local(on-premise) LLM model, for example, model serving by `vLLM`(refer to blog https://k8sgpt.ai/blog/post-6/)
Problem was met when request from k8sgpt  has NO default MaxToken value.
From the log of vLLM
you will see `temperature=0.7` and `max_tokens=16`
such a small max_tokens will cause below issue: the answers from LLM was truncated.
So this fix try to make the value explicit ,   just like what was done in https://github.com/k8sgpt-ai/k8sgpt/blob/main/pkg/ai/cohere.go#L66
With this fix , we will see the new log from vLLM become  better :
when swich back to online openAI, the …

feat: openAI explicit value for maxToken and temperature

---

cmd/serve/serve.go

Extension of this [PR](https://github.com/k8sgpt-ai/k8sgpt/pull/659)
We add temperature as an env variable to also enable the k8s operator to configure it

feat: adding temperature to server mode

---

README.md
cmd/auth/add.go
cmd/auth/auth.go
pkg/ai/amazonsagemaker.go
pkg/ai/iai.go
pkg/analyzer/ingress.go

Closes #730
- Adds Amazon SageMaker as a backend
- adds `endpointname` flag to `k8sgpt auth`
- `endpointname` and `providerRegion` are required for amazonsagemaker backend 
- Updated README.md
Co-authored-by: Mateusz Zaremba

feat: amazonsagemaker AI provider

---

pkg/analyzer/pod.go

The OOMKilled is a very short-lived container state, probably around few seconds. As soon as kubernetes sees a pod in OOMKilled state it tries to restart the pod. If pod is getting terminated and getting restarted multiple times, kubernetes marks it under CrashloopBackoff state. The event message in CrashloopBackoff state does not capture OOMKilled context. When k8sgpt PodAnalyzer sees a pod in CrashloopBackoff state it should check why pod is getting terminated/restarting (LastTerminatedState) and add it in the failure message. The following is the before and after results for containers in CrashloopBackoff state
Before
```
3 opa/opa-849dcb7499-9chrt(Deployment/opa)
- Error: back-off 5m0s restarting failed container=kube-mgmt pod=opa-849dcb7499-9chrt_opa(7f8061d3-3603-49d6-8e03-77cb4b1bbe …
```

feat: add last termination state when pod is in CrashloopBackoff

---

pkg/server/server.go
pkg/server/server_test.go

This PR is in response to #809 
Closes # 

chore: added basic server startup test

---

go.mod
go.sum

Closes # 
bump docker go `golang.org/x/crypto` & `github.com/containerd/containerd` dependency 
Fixes CVE [GHSA-45x7-px36-x8w8](https://github.com/advisories/GHSA-45x7-px36-x8w8) & [GHSA-7ww5-4wqc-m92c](https://github.com/advisories/GHSA-7ww5-4wqc-m92c)

deps: go module bump to fix CVE: GHSA-45x7-px36-x8w8 & GHSA-7ww5-4wqc-m92c

---

cmd/cache/cache.go
pkg/cache/cache.go
pkg/cache/s3_based.go
pkg/server/server.go
pkg/server/server_test.go
pkg/util/util.go

chore: lint fixes

---

pkg/ai/amazonbedrock.go
pkg/ai/amazonsagemaker.go
pkg/ai/azureopenai.go
pkg/ai/cohere.go
pkg/ai/iai.go
pkg/ai/localai.go
pkg/ai/noopai.go
pkg/ai/openai.go

[GoogAI PR](https://github.com/k8sgpt-ai/k8sgpt/pull/829/files#diff-73c9c2eb51f34cd7def45a991f84e9b8e7428c4d8d541553839b81e98f91708aR26) has added a new constant to determine the AI client name. This PR unifies and adds a new constant to determine the AI client name on all providers.

feat: unify aiClientName const for all providers

---

.goreleaser.yaml

`tap` got replaces by `repository` and is now deprecated.
This deprecation warning can also be seen in the goreleaser logs:
>     • DEPRECATED: brews.tap should not be used anymore, check https://goreleaser.com/deprecations#brewstap for more info
https://github.com/k8sgpt-ai/k8sgpt/actions/runs/7521548656/job/20472514099

ci: replace deprecated brew config

---

.github/workflows/golangci_lint.yaml
cmd/cache/add.go
cmd/generate/generate.go
pkg/analyzer/gateway.go
pkg/analyzer/gateway_test.go
pkg/integration/trivy/analyzer.go
pkg/server/integration.go
pkg/server/server.go
pkg/server/server_test.go

chore: linting improvements and catching false positives

---

README.md
go.mod
go.sum
pkg/ai/huggingface.go
pkg/ai/iai.go

Closes #828  
added huggingface provider.
for HF package, i use https://github.com/hupe1980/go-huggingface. i think this is more fit for k8sgpt code than [this](https://github.com/Kardbord/hfapigo). Let me know if you think differently
Also, HF api request requires `maxtokens` less than or equal to 500. but k8sgpt`s default maxtokens is 2048 so users will get below output if they don't update or set `maxtokens`. 
How do you think setting huggingface`s default `maxtokens` to 500 if it is set k8sgpt`s default 2048?
```bash
> ./bin/k8sgpt analyze -f Service -e
0% | …
```

feat: add huggingface provider

---

cmd/generate/generate.go
cmd/serve/serve.go
pkg/analyzer/gateway_test.go
pkg/analyzer/gatewayclass.go
pkg/analyzer/gatewayclass_test.go
pkg/analyzer/httproute.go
pkg/analyzer/httproute_test.go
pkg/integration/prometheus/config_analyzer.go
pkg/server/integration.go
pkg/server/server.go
pkg/server/server_test.go

Closes # #917 
- This pull request addresses all existing lint errors in the codebase. The primary goal was to improve code quality and maintainability by adhering to our established linting rules. 
- After making these changes, I ran the linter again to confirm that all lint errors have been fixed. The linter completed without any errors or warnings. 
- In addition to linting, I also ran our unit tests to ensure that these changes did not break any existing functionality. All tests passed successfully.
Current make lint command log screenshot
Some of the lint errors have been fixed in pull request #916. To ensure the lint command works successfully, please merge both PRs.

fix: lint errors

---

cmd/serve/serve.go

Closes #968 
Removed the shorthand for the `http` flag in the serve command because it was contradicting with the shorthand of the `help` command which is automatically added on execution if the `help` flag is not already defined.

fix: shorthand for the http flag in serve command

---

cmd/serve/serve.go
pkg/ai/azureopenai.go
pkg/ai/iai.go
pkg/ai/openai.go

Closes https://github.com/k8sgpt-ai/k8sgpt-operator/issues/307
This PR adds proxyEndpoint for openai and azureopenai config for the request to be reached through an HTTP like proxy. Tested this manually on azureopenai and openai. This can be used by using an Environment Variable `K8SGPT_PROXY_ENDPOINT` while using the tool.

feat: add proxysettings for azureopenai and openai

---

pkg/analyzer/mutating_webhook_test.go

This commit introduces comprehensive tests for the mutating webhook analyzer defined in the `pkg/analyzer` package.
Adding these tests increases the code coverage of the `mutating_webhook.go` file to almost 95%.

test: added tests for mutating webhook analyzer

---

pkg/analyzer/pdb.go
pkg/analyzer/pdb_test.go

This commit introduces comprehensive tests for the `PodDisruptionBudget` analyzer defined in the `pkg/analyzer` package.
Adding these tests increases the code coverage of the `pdb.go` file to >96%.
Additionally, a potential crash in case of empty or nil PDB status conditions has been addressed.

test: added tests for the PDB analyzer

---

pkg/analyzer/pvc.go
pkg/analyzer/pvc_test.go
pkg/analyzer/rs_test.go

This commit introduces comprehensive tests for the `PersistentVolumeClaim` analyzer defined in the `pkg/analyzer` package.
Adding these tests increases the code coverage of the `pvc.go` file to
>95%.
I also made minor modifications to the ReplicaSet test to ensure all expectations were met.

test: added tests for the PVC analyzer

---

pkg/analyzer/pvc_test.go

With the addition of the latest changes, the missing test case when an event happens after the currently set latest event has been covered.
Partially Addresses: https://github.com/k8sgpt-ai/k8sgpt/issues/889

test: added missing test case for events.go

---

pkg/analyzer/cronjob.go
pkg/analyzer/cronjob_test.go
pkg/analyzer/pdb_test.go
pkg/analyzer/rs_test.go
pkg/analyzer/service_test.go

- Fixed a small bug where pre-analysis was incorrectly appended to the results every time at the end of the for loop. This caused the result for a single cronjob failure to be appended multiple times in the final results.
- Added missing test cases to ensure proper testing of the CronJob analyzer. The addition of these missing test cases has increased the code coverage of this analyzer to over 96%.
Partially Addresses: https://github.com/k8sgpt-ai/k8sgpt/issues/889

test: added missing tests for the CronJob analyzer

---

renovate.json

Closes #1008 
Fixes the renovate config file and make the groups more visible,
I am adding 4  dependency groups "golang, k8s, prometheus and azure"; golang's and k8s' dep updates are  quite often. This is the first iteration (with a valid renovate.conf file) to bundle our deps to avoid PR fatigue
I ran it against renovate-config-validator and was happy

chore: update renovate config and bundle deps in groups

---

pkg/analyzer/pod.go
pkg/analyzer/pod_test.go

- Fixed a small bug where failures were being appended multiple times for CrashLoopBackOff and ContainerCreating container status reasons.
- Added missing test cases to ensure proper testing of the Pod analyzer. The addition of these missing test cases has increased the code coverage of this analyzer to 92%.

test: added missing tests for the Pod analyzer

---

cmd/serve/serve.go
pkg/ai/openai.go

Closes #1052 
This PR allows for setting topP from the config yaml for the `openai` provider.
I took the liberty of opening both the issue and the PR fixing it, please let me know if I should follow any other process.

fix: set topP from config

---

pkg/analyzer/log.go
pkg/analyzer/log_test.go

* Added new tests for `LogAnalyzer` defined in the `pkg/analyzer` package. Increased the code coverage of the `log.go` file to >90%
* Added `fake logs` string to the `errorPattern` to enable the discovery of error logs during the tests.
TODO: Find a method to edit logs of the containers defined in the Kubernetes client config.

test: added tests for the log analyzer

---

pkg/integration/aws/aws.go

Closes #1113 
support AWS_PROFILE when using aws integration.
so if there is profile in `~/.aws/credentials` we can use `AWS_RPOFILE=profile k8sgpt ~~`
or if there is `default` profile in `~/.aws/credentials` we can just `k8sgpt ~~`

feat: support AWS_PROFILE

---

cmd/auth/add.go
cmd/auth/auth.go
cmd/serve/serve.go
pkg/ai/amazonsagemaker.go
pkg/ai/googlegenai.go
pkg/ai/googlevertexai.go
pkg/ai/huggingface.go
pkg/ai/iai.go

This commit adds Top-K sampling, a feature that allows users to control the randomness of the generated text by specifying the number of most probable next words considered by the model. This enhances user control and potentially improves the quality of the generated outputs.
Closes #1105

feat: implement Top-K sampling for improved user control

---

cmd/auth/add.go
cmd/auth/auth.go
go.mod
go.sum
pkg/ai/iai.go
pkg/ai/ocigenai.go

Closes #1049 
Adds Oracle Cloud Infrastructure (OCI) GenAI service as a backend for k8sgpt. 
- [] My pull request adheres to the code style of this project
- [] My code requires changes to the documentation
- [] I have updated the documentation as required
- [] All the tests have passed
CompartmentId is added as a new parameter for OCI GenAI.

feat: oci genai

---

cmd/auth/add.go

see some build failure in https://github.com/Homebrew/homebrew-core/pull/171893
```
==> /home/linuxbrew/.linuxbrew/Cellar/k8sgpt/0.3.31/bin/k8sgpt analyze --explain --filter=Service
panic: unable to redefine 'c' shorthand in "add" flagset: it's already used for "topp" flag
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0001c6e00, 0xc00055bae0)
github.com/spf13/pflag@v1.0.5/flag.go:874 +0x3f5
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0001c6e00, {0x4bf0978, 0x6868708}, {0x433bbd3, 0x4}, {0x4bb9e70, 0x1}, {0x444b73e, 0xca})
github.com/spf13/pflag@v1.0.5/flag.go:831 +0x105
github.com/spf13/pflag.(*FlagSet).VarP(...)
github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).Int32VarP(0x4427598?, 0x5e?, {0x433bbd3?, 0x10?}, {0x4bb9e70?, …
```

fix: remove shorthand flag for topp option in add command

---

.goreleaser.yaml

chore: updated goreleaser config

---

README.md
go.mod
go.sum
pkg/ai/iai.go
pkg/ai/watsonxai.go

Closes # 
Add IBM watsonx ai as AI provider for k8sGPT.
Document: https://github.com/k8sgpt-ai/docs/pull/107
The API key and project ID are hidden for security
```shell
$ k8sgpt auth add -b watsonxai -m ibm/granite-13b-chat-v2
watsonxai added to the AI backend provider list
$ export WATSONX_API_KEY=**************************
$ export WATSONX_PROJECT_ID=**************************
$ k8sgpt analyze -b watsonxai --explain
100% || (3/3, 26 it/min)
AI Provider: watsonxai
0: Service openshift-machine-api/machine-api-controllers()
- Error: Service has no endpoints, expected label k8s-app=controller
Error: Service has no endpoints, expected label k8s-app=controller
Solution: Check the pod's annotations and ensure the label `k8s-app=controller` is present. If it's not, apply the label using the …
```

feat: add watsonx ai provider

---

pkg/analysis/analysis.go

Closes # 
- add parallelism when custom analysis is run
- remove redundant parallelism declaration when classic analysis is run

feat: custom analysis paralelism

---

pkg/ai/watsonxai.go

Closes # 
Add default maxToken value of watsonxai backend.

fix: add default maxToken value of watsonxai backend

---

cmd/serve/serve.go

Closes https://github.com/k8sgpt-ai/k8sgpt/issues/1206

fix: segmentation violation during serve

---

go.mod
pkg/server/server.go

Closes #1208  
Set logger for controller-runtime.
Testing done:
- `make docker-build` -> ok
- After applying the newly built Docker image in k8sgpt-operator, this log `[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.` is no longer present.

fix: set logger for controller-runtime

---

charts/k8sgpt/templates/deployment.yaml

Closes # 
When `.Values.deployment.securityContext` is empty (`{}`), the helm installation fails with
```
Error: YAML parse error on k8sgpt/templates/deployment.yaml: error converting YAML to JSON: yaml: lin
e 24: mapping values are not allowed in this context                                                 
Use --debug flag to render out invalid YAML 
```
This fixes the rendering.

fix: helm chart security context rendering if empty

---

cmd/serve/serve.go

Closes # 
In the ibmwatsonxai AI backend, it requires `providerId` and it is indispensable. Refer to [PR](https://github.com/k8sgpt-ai/k8sgpt/pull/1190). Therefore, we need to add providerId parameter in the `serve` mode so that we can enable ibmwatsonxai in k8sgpt-operator to pass the providerId parameters.

fix: add providerId to serve mode

---

go.mod
pkg/ai/amazonbedrock.go

Closes # (https://github.com/k8sgpt-ai/k8sgpt/issues/1329)
Add support for AWS Bedrock model claude sonnet 3.5 and claude sonnet 3.5v2

feat: add new AWS Bedrock model ids

---

pkg/ai/amazonbedrock.go
pkg/ai/amazonbedrock_test.go
pkg/ai/bedrock_support/completions.go

Closes # https://github.com/k8sgpt-ai/k8sgpt/issues/1442
Taking advantage of the naming conversion of the AWS Bedrock inference profile, match inference profile arn to the predefined enum of model ID

feat: add a naive support of bedrock inference profile

---

cmd/analyze/analyze.go
cmd/root.go
cmd/root_test.go
go.mod
go.sum
pkg/analysis/analysis.go
pkg/analysis/analysis_test.go
pkg/util/util.go

Closes #1399
This PR adds a -v / --verbose flag to the k8sgpt CLI to enable detailed output for debugging and troubleshooting.
The flag is registered as a `PersistentFlag` in `root.go`, stored via `viper` during initialization, and checked where needed to control verbose output.
Example Usage:
```
k8sgpt -v analyze  
k8sgpt analyze --verbose  
```
The documentation should be updated to include the new verbose flag and explain its usage in the CLI.

feat: add verbose flag to enable detailed output

---

cmd/auth/update.go

Closes #1496
This PR fixes a panic in `k8sgpt auth update`. 
Before:
```
k8sgpt auth update -b test
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/k8sgpt-ai/k8sgpt/cmd/auth.init.func9(0x6b74ac0, {0xc000598e80, 0x0, 0x3ec6095?})
/home/runner/work/k8sgpt/k8sgpt/cmd/auth/update.go:93 +0x6ec
github.com/spf13/cobra.(*Command).execute(0x6b74ac0, {0xc000598e60, 0x2, 0x2})
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x6b733c0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/k8sgpt-ai/k8sgpt/cmd.Execute({0x451ed84?, 0x0?}, …
```

fix: panic in k8sgpt auth update

---

README.md
pkg/analyzer/analyzer.go
pkg/analyzer/job.go
pkg/analyzer/job_test.go

Closes #1503
Relate to https://github.com/k8sgpt-ai/k8sgpt/issues/1474#issuecomment-2833527637
This PR introduces job analyzers to enhance the capabilities of K8sGPT:
- Analyzes suspended jobs.
- Analyzes failed jobs.
These job analyzers will assist users in better identifying job execution issues within their Kubernetes clusters.
If necessary in the future, further analysis can be conducted based on the pods generated by jobs and the events associated with jobs. However, to keep this PR concise, such content has not been included in this submission.
The output is like:
```
root@kay200:~/oss/k8sgpt# ./bin/k8sgpt analyze  --filter Job --explain -c
100% |██████████████████████████████████████████████████████████| (1/1, 15 it/min)
AI Provider: openai
0: Job default/failed-job()
- Error: Job …
```

feat: new job analyzer

---

pkg/ai/googlevertexai.go

Related to #1516  
- Added support for latest and legacy stable models to date for the Google Vertex AI provider: 
-- gemini-2.5-pro       
-- gemini-2.5-flash     
-- gemini-2.0-flash    
-- gemini-2.0-flash-lite
-- gemini-1.5-pro-002*
-- gemini-1.5-flash-002*
- Changed default model to `gemini-2.5-pro` instead of the retired `gemini-1.0-pro-001`
- [v ] My pull request adheres to the code style of this project
Based on [Model versions and lifecycle webpage](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions#gemini-model-versions)

feat: add latest and legacy stable models

---

SUPPORTED_MODELS.md
pkg/ai/amazonbedrock.go

Closes #1542 
This PR adds support for two new APAC region Claude models in the Amazon Bedrock AI provider to enable users in APAC regions to access the latest Claude models with improved performance and lower latency.

feat: add APAC region Claude models support for Amazon Bedrock

---

README.md
pkg/analyzer/analyzer.go
pkg/analyzer/catalogsource.go
pkg/analyzer/catalogsource_test.go
pkg/analyzer/clusterserviceversion.go
pkg/analyzer/clusterserviceversion_test.go
pkg/analyzer/installplan_test.go
pkg/analyzer/instalplan.go
pkg/analyzer/operatorgroup.go
pkg/analyzer/operatorgroup_test.go
pkg/analyzer/subscription.go
pkg/analyzer/subscription_test.go

This PR introduces five new analyzers for the CNCF project **OLMv0**:
- ClusterServiceVersion
- Subscription
- InstallPlan
- OperatorGroup
- CatalogSource
Additionally, it adds support for unit tests using the dynamic fake client, enabling accurate simulation of non-core Kubernetes resources such as CRDs for testing purposes.
```
==> Running unit tests 
[CMD] cd /Users/bandrade/redhat/repositories/k8sgpt && go test -v ./pkg/analyzer -run 'TestClusterServiceVersionAnalyzer|TestSubscriptionAnalyzer|TestInstallPlanAnalyzer|TestCatalogSourceAnalyzer|TestOperatorGroupAnalyzer'
=== RUN   TestCatalogSourceAnalyzer_UnhealthyState_ReturnsResult
--- PASS: TestCatalogSourceAnalyzer_UnhealthyState_ReturnsResult (0.00s)
=== RUN   TestCatalogSourceAnalyzer_HealthyOrNoState_Ignored
--- PASS: …
```

feat: add ClusterServiceVersion, Subscription, InstallPlan, OperatorGroup, and CatalogSource analyzers
